<?xml version="1.0"?>
<!--This is a draft spec for ERNIE seedsets in xml format with an internal DTD -->
<!--This format is used for gen1 seedsets for network construction in ERNIE case studies-->
<!--Author: George Chacko-->
<!--Date: 10/19/2017-->
<!DOCTYPE case_study [
<!ELEMENT case_study (therapeutic | diagnostic | intervention)>
<!ELEMENT therapeutic (fda , pubmed , ct , patent)>
<!ELEMENT fda (active_ingredient , brand_name , (nda | bla)* , approval_date , source , medical_review_pmid* , fda_other_pmid*)>
<!ELEMENT active_ingredient (#PCDATA)>
<!ELEMENT brand_name (#PCDATA)>
<!ELEMENT nda (#PCDATA)>
<!ELEMENT bla (#PCDATA)>
<!ELEMENT approval_date (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT medical_review_pmid (#PCDATA)>
<!ELEMENT fda_other_pmid (#PCDATA)>
<!ELEMENT pubmed (pubmed_ct_preapp_pmid* , pubmed_ct_postapp_pmid* , pubmed_preapp_pmid+ , pubmed_postapp_pmid+ , pubmed_review_pmid+)>
<!ELEMENT pubmed_ct_preapp_pmid (#PCDATA)>
<!ELEMENT pubmed_ct_postapp_pmid (#PCDATA)>
<!ELEMENT pubmed_preapp_pmid (#PCDATA)>
<!ELEMENT pubmed_postapp_pmid (#PCDATA)>
<!ELEMENT pubmed_reviews_pmid (#PCDATA)>
<!ELEMENT ct (ct_preapp_reference_pmid* , ct_postapp_reference_pmid* , ct_preapp_publication_pmid* , ct_postapp_publication_pmid* , ct_preapp_nct* , ct_postapp_nct*)>
<!ELEMENT ct_preapp_reference_pmid (#PCDATA)>
<!ELEMENT ct_postapp_reference_pmid (#PCDATA)>
<!ELEMENT ct_preapp_publication_pmid (#PCDATA)>
<!ELEMENT ct_postapp_publication_pmid (#PCDATA)>
<!ELEMENT ct_preapp_nct (#PCDATA)>
<!ELEMENT ct_postapp_nct (#PCDATA)>
<!ELEMENT patent (npl_pmid* , pl_USpatentno*)>
<!ELEMENT npl_pmid (#PCDATA)>
<!ELEMENT pl_USpatentno (#PCDATA)>
]>
<drug>
  <fda>
    <active_ingredient>buprenorphine hydrochloride</active_ingredient>
    <brand_name>Buprenex</brand_name>
    <nda>018410</nda>
    <nda>018401</nda>
    <fda_approval_date>12/29/81</fda_approval_date>
    <source>drugs@fda</source>
    <buprenorphine_fda_medical_review_pmid>00000</buprenorphine_fda_medical_review_pmid>
    <buprenorphine_fda_medical_review_pmid/>
    <buprenorphine_fda_other_pmid>238862</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>4155750</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>945347</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>235626</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>6688</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>2687</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>1238136</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>4851667</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>1275955</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>4597802</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>16506</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>4211992</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>409449</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>409448</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>414464</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>205747</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>201474</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>19709</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>698486</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>30820</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>1097258</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>34176</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>828466</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>747691</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>230881</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>380616 </buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>223616</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>572694</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid>000000</buprenorphine_fda_other_pmid>
    <buprenorphine_fda_other_pmid/>
  </fda>
  <patent>
    <pl_USpatentno>US3433791</pl_USpatentno>
    <buprenorphine_npl_pmid>00000</buprenorphine_npl_pmid>
    <buprenorphine_npl_pmid/>
  </patent>
  <ct>
    <ct_preapp_references_pmid>00000</ct_preapp_references_pmid>
    <ct_preapp_references_pmid/>
    <ct_preapp_publication_pmid>00000</ct_preapp_publication_pmid>
    <ct_preapp_publication_pmid/>
    <ct_preapp_publication_pmid/>
    <ct_postapp_reference_pmid>831502</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  1334156</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  1697056</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  2484297</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  3397865</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  3583214</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  6760767</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  7714228</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  7714228</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  7734458</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  8181201</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  8373940</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  8555282</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  8624183</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  8704003</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  9107051</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>  9794682</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 10109801</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 10359226</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 10615719</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 10735542</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 10842426</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 10867295</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 10868247</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 10910854</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11015800</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11027904</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11166974</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11224254</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11354213</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11376918</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11464356</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11773815</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11847954</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 11915063</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 12170039</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 12357165</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 12411815</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 12467992</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 12649385</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 12731680</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 12924748</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 14551424</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 14570643</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15354916</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15450644</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15450648</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15495080</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15516351</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15577542</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15603008</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15734226</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15781540</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15812611</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15943939</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 15957687</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16010170</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16154698</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16229972</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16249678</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16298066</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16368840</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16445556</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16457716</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16508405</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16595350</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16769444</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16918095</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 16939945</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 17055063</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 17065895</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 17079636</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 17372805</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 17509814</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 18283247</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 18425880</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 18585645</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 18694901</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 18774509</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 18794671</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 18794671</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 18804923</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19047522</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19089500</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19089508</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19192240</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19266708</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19309185</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19401688</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19403243</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19461836</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19625142</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19631928</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19823204</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19874163</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19918165</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 19925973</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20009936</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20014912</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20180664</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20180667</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20307795</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20407975</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20407980</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20473351</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20682186</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20716304</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20797916</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20842024</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20842024</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20868741</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20887580</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20925688</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 20940383</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21042200</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21054613</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21142534</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21145035</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21170143</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21330586</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21519308</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21535372</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21538146</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21676892</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21697669</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21768936</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21861411</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21889122</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21956078</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 21956081</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22005659</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22227421</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22227428</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22323375</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22379567</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22430023</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22512363</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22525903</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22546608</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22581379</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22634908</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22651957</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22680789</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22707880</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22798528</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22829027</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 22983894</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23106923</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23159699</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23398230</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23480249</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23523131</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23530789</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23647815</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23702611</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23727040</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23739025</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 23796584</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 24120973</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 24217469</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 24315147</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 24320787</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 24500338</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 24740719</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 24985936</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25035906</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25084802</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25178815</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25183042</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25191915</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25330017</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25336055</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25364994</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25392564</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25622120</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 25775440</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 26158353</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 26388962</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 26517324</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 26720857</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid> 27464203</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid/>
    <ct_postapp_reference_pmid/>
    <ct_postapp_publication_pmid>25919527</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 20513828</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 11351930</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 25603822</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 10928310</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317600</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317595</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317592</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317590</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317596</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317597</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317602</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317589</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317598</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317591</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21317588</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 24227768</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 22409388</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21807566</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 22921476</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 11058673</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 22845044</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 23359655</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 19726139</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 21945130</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 18694901</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 20925688</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 20959867</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 25666027</ct_postapp_publication_pmid>
    <ct_postapp_publication_pmid> 20672450</ct_postapp_publication_pmid>
  </ct>
  <pubmed>
    <pubmed_preapp_pmid>7150869</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6984472</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6298835</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6298527</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6294424</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7126409</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7120124</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6288917</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6126640</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7140531</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7155049</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7124308</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6181259</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6283067</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6805715</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6281389</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7082534</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6122613</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7084303</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6282596</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7066163</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7066147</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7066145</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7066139</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7047580</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6811932</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6811921</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6811910</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6181414</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6126811</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7066127</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7039643</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6952112</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7057390</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6174908</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7127370</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7055528</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6760767</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6292982</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6276633</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6950300</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7041936</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6802995</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6271322</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7304894</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7306425</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7198266</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6115924</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6270490</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7263931</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7258587</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6262686</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7324833</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6262095</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7293215</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7224117</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7229117</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6783946</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7202515</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7319134</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7232665</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6794327</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6791015</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6785803</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6456287</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6262856</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7018155</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6107711</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7438685</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6107472</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7439255</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7437209</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7220432</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7004250</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6252996</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6106780</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7407029</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7435902</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6990950</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7352279</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7360334</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7371972</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7250147</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6768078</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>510395</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>391321</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>509142</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>526414</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>497691</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>115537</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>383195</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>466334</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>583326</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>483080</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>484814</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>458815</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>474948</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>444978</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>286917</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>453488</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>421663</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>421114</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>378645</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>572694</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>552286</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>547663</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>547656</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>465292</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>465291</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>380617</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>380616</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>223616</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>728741</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>747691</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>722743</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>34176</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>30820</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>698486</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>666936</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>352372</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>215096</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>744302</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>414464</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>334210</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>409449</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>409448</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>869156</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>334206</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>321103</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>14772</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>338392</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>337748</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>31641</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>974396</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>945347</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6688</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>1032070</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>1015212</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>801583</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>801582</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2687</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4851667</pubmed_preapp_pmid>
    <pubmed_postapp_pmid>29083570</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29084357</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29073311</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29068826</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29065377</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29064938</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29056859</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29054032</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29052805</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29051703</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29049469</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29049278</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29049122</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29048415</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29047196</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29046888</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29045307</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29043488</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29040331</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29036723</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29035705</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29032916</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29025085</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29020387</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29019444</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29016376</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28973618</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28972704</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28968623</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28968188</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28967123</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28966276</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28965857</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28962922</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28961489</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28957756</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28948894</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28944090</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28935058</pubmed_postapp_pmid>