<?xml version="1.0"?>
<!--This is a draft spec for ERNIE seedsets in xml format with an internal DTD -->
<!--This format is used for gen1 seedsets for network construction in ERNIE case studies-->
<!--Author: George Chacko-->
<!--Date: 12/01/2017-->
<!DOCTYPE case_study [
<!ELEMENT case_study (therapeutic | diagnostic | intervention)>
<!ELEMENT therapeutic (fda , pubmed , ct , patent)>
<!ELEMENT fda (active_ingredient , brand_name , (nda | bla)* , approval_date , source , medical_review_pmid* , fda_other_pmid*)>
<!ELEMENT active_ingredient (#PCDATA)>
<!ELEMENT brand_name (#PCDATA)>
<!ELEMENT nda (#PCDATA)>
<!ELEMENT bla (#PCDATA)>
<!ELEMENT approval_date (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT medical_review_pmid (#PCDATA)>
<!ELEMENT fda_other_pmid (#PCDATA)>
<!ELEMENT pubmed (pubmed_preapp_pmid)+>
<!ELEMENT pubmed_preapp_pmid (#PCDATA)>
<!ELEMENT ct (ct_preapp_reference_pmid* , ct_preapp_publication_pmid*)>
<!ELEMENT ct_preapp_reference_pmid (#PCDATA)>
<!ELEMENT ct_preapp_publication_pmid (#PCDATA)>
<!ELEMENT ct_preapp_nct (#PCDATA)>
<!ELEMENT ct_postapp_nct (#PCDATA)>
<!ELEMENT patent (npl_pmid* , pl_USpatentno*)>
<!ELEMENT npl_pmid (#PCDATA)>
<!ELEMENT pl_USpatentno (#PCDATA)>
]>
<drug>
  <fda>
    <brand_name>Yervoy</brand_name>
    <active_ingredient>ipilimumab</active_ingredient>
    <bla>125377 </bla>
    <source>drugs@fda</source>
    <ipilimumab_fda_medical_review_pmid>20086001</ipilimumab_fda_medical_review_pmid>
    <ipilimumab_fda_other_pmid>12087419</ipilimumab_fda_other_pmid>
  </fda>
  <patent>
    <pl_USpatentno>US6984720 B1</pl_USpatentno>
    <ipilimumab_npl_pmid>10096554</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>10201965</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>10430624</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>10811122</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>1334116</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>1475190</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>1714933</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>1847722</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2156778</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2164219</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2171783</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2465550</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2540528</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2794510</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2940206</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3021470</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3134293</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3220103</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3496540</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3500211</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>6274961</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>6458039</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7494109</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7543139</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7543510</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7759881</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7846057</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7882171</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8018598</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8075633</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8159246</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8347558</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8348148</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8475122</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8596936</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8671638</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8676074</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8676075</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9020839</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9036940</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9104819</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9203422</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9221747</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9223321</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9354465</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9430233</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9449722</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9551948</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9631000</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9631008</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9687526</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9707601</ipilimumab_npl_pmid>
  </patent>
  <ct>
    <ct_preapp_references_pmid>16283570</ct_preapp_references_pmid>
    <ct_preapp_references_pmid>16301685</ct_preapp_references_pmid>
    <ct_preapp_publication_pmid>12826605</ct_preapp_publication_pmid>
    <ct_preapp_publication_pmid>16087944</ct_preapp_publication_pmid>
    <ct_preapp_publication_pmid>16283570</ct_preapp_publication_pmid>
    <ct_preapp_publication_pmid>20842054</ct_preapp_publication_pmid>
  </ct>
  <pubmed>
    <pubmed_preapp_pmid>23226069</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23049279</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23037483</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23024154</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22904648</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22844202</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22778766</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22778760</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22677983</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22666217</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22566975</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22530324</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22477725</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22459268</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22453019</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22453017</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22443134</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22434096</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22432863</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22423265</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22423263</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22419879</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22409862</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22406592</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22402694</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22397654</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22396993</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22396291</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22393198</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22385525</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22385436</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22382362</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22375995</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22370387</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22350184</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22346364</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22339359</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22338019</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22333219</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22326924</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22326922</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22326921</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22306905</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22300855</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22468871</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22271879</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22270215</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22270078</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22267918</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22256820</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22253555</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22231551</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22219590</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22215850</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22209376</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24451817</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24451790</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24451730</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23788912</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23788878</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22203769</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22196270</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22193102</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22186141</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22180676</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22146893</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22142824</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22074657</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22130166</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22130164</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22124094</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22123319</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22109345</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22091682</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22082642</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22077981</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22077831</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22071969</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22069060</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22051508</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22047582</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22046181</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22044200</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22036643</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22033581</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22030452</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22028422</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22020206</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22010182</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22006439</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21991906</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21991905</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21991904</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21990407</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21990398</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21957431</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21954698</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21952276</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21951748</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21933959</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21930211</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21917607</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21914583</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21900791</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21900389</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21881038</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21850925</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21843079</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21833591</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21821307</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21815696</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21810572</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21807763</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21806402</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21804596</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21802280</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21788973</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21785279</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21785048</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21777474</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21770473</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21748753</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21737695</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>25373277</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21708958</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21701442</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21700764</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21693727</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21668044</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21659402</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21639810</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21629286</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21561409</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21554088</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21551417</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21515855</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21505108</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21470540</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21465316</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21455150</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21427556</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21365253</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21357649</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21317818</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21311328</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21294474</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21294473</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21294472</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21294471</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21282973</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21264545</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21242854</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21235437</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21220617</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21204754</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23789039</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21170646</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21150603</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21121842</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21111961</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21106722</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21090563</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21088057</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21083648</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21080797</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21074069</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21074065</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21074064</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21074063</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21074062</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21074061</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21074060</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21074058</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20957980</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20943639</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20853321</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20842054</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20818880</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20811384</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20734041</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20713164</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20698719</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20697383</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20693841</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20671754</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20635901</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20616954</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20609175</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20593249</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20563707</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20525992</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20460488</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20383346</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20307219</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20216240</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20152761</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20147741</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20143434</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20140276</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20082117</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20052966</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20004617</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19952852</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19934296</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19934295</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19808874</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19793711</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19752745</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19679015</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19671877</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19650371</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19648604</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19639414</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19587352</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19557204</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19556898</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19544692</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19544689</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19538054</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19512947</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19507029</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19474123</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19318477</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19242368</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19238020</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19238009</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19236253</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19198837</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19147575</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19139884</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19136343</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19104936</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19088949</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19074257</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19052265</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19052742</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19018089</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19001147</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19001144</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18974373</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18838703</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18832811</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18818309</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18806898</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18780859</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18716842</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18665147</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18612161</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18597009</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18545145</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18537753</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18528295</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18390726</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18287062</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18279066</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18198818</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18049334</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18027152</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>18000991</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17982122</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17922073</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19543441</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17696822</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17673617</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17520107</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17440629</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17363537</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17327854</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17289891</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17289867</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17198092</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>17013086</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>16801985</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>16710025</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>16370382</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>16283570</pubmed_preapp_pmid>
  </pubmed>
</drug>
